services:
  - type: web
    name: agario-python-ai
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
